services:
  mountebank:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: rjnpnigrhi/mountebank-go:sha-2ba75b5
    container_name: mountebank-go
    network_mode: "host"
    # command: start --port 2525 --loglevel info --host 0.0.0.0 --configfile /app/impostersejs/imposters.ejs --allowInjection --datadir /app/data
    command: start --port 2525 --loglevel info --host 0.0.0.0 --configfile /mountebank-templates/imposters.ejs --allowInjection
    environment:
      - MB_LOG_LEVEL=info
    volumes:
      - ../mountebank-templates:/mountebank-templates
      # Optional: Mount for persistent data
      # - ./data:/app/data
    restart: unless-stopped

